docs_dir: notes
site_name: Marco Labarile - Notes
site_description: Notes about various topics, courses, books, etc.
site_author: Marco Labarile
site_url: https://marcolabarile.me/notes/
repo_name: labarilem/notes
repo_url: https://github.com/labarilem/notes
edit_uri: ""
google_analytics:
  - UA-117745201-1
  - auto
theme:
  name: material
  static_templates:
    - 404.html
  include_search_page: false
  search_index_only: true
  language: en
  feature:
    tabs: false
  palette:
    primary: green
    accent: green
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon-16x16.png
  logo:
    icon: 
extra:
  social:
    - type: github-alt
      link: https://github.com/labarilem
    - type: linkedin
      link: https://www.linkedin.com/in/marcolabarile/
markdown_extensions:
  - markdown.extensions.attr_list
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: ""
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra_css:
  - 'assets/styles/extra.css'
pages:
  - Home: index.md
  - OAuth 2.0 and OpendID Connect:
      - Home: oauth2-and-openid-connect/index.md
      - JWT (JSON Web Token): oauth2-and-openid-connect/jwt.md
      - OAuth 2.0: oauth2-and-openid-connect/oauth2.md
      - OpenID Connect: oauth2-and-openid-connect/openid-connect.md
  - Building microservices:
      - Home: building-microservices/index.md
      - Microservices: building-microservices/microservices.md
      - Evolutionary architects: building-microservices/evolutionary-architects.md
      - How to model services: building-microservices/how-to-model-services.md
      - Integration: building-microservices/integration.md
      - Splitting the monolith: building-microservices/splitting-the-monolith.md
      - Deployment: building-microservices/deployment.md
      - Testing: building-microservices/testing.md
      - Monitoring: building-microservices/monitoring.md
      - Security: building-microservices/security.md
      - Conway's Law and System Desing: building-microservices/conway.md
      - Microservices at Scale: building-microservices/microservices-at-scale.md
      - Bringing It All Together: building-microservices/conclusion.md
  - Bitcoin and cryptocurrency technologies:
      - Home: bitcoin-and-cryptocurrency-technologies/index.md
      - Cryptographic hash functions: bitcoin-and-cryptocurrency-technologies/crypto-hash-functions.md
      - Digital signature: bitcoin-and-cryptocurrency-technologies/digital-signature.md
      - Hash pointers: bitcoin-and-cryptocurrency-technologies/hash-pointers-and-data-structures.md
      - Centralization and decentralization: bitcoin-and-cryptocurrency-technologies/centralization-vs-decentralization.md
      - Distributed consensus: bitcoin-and-cryptocurrency-technologies/distributed-consensus.md
